version: '3'
services:
  helloworldarm:
    image: hivetechnologies/powershellarm
    deploy:
      placement:
        constraints:
          - engine.labels.architecture == armv6l
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  visualizer:
    image: alexellis2/visualizer-arm
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8080:8080/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webnet

networks:
  webnet: